# Configuration for using acid

include = ["../base.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
bootloader = {}
acid = {}
coreutils = {}
# TODO: Does this need escalated?
escalated = {}
ion = {}
ipcd = {}
ptyd = {}

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
escalated
"""

[[files]]
path = "/etc/init.d/10_acid"
data = """
export RUST_BACKTRACE full
acid
acid create_test
acid switch
acid tls
acid thread
shutdown
"""
