# Default desktop configuration

include = ["../server-minimal.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256

# Package settings
[packages]
audiod = {}
drivers = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}

[[files]]
path = "/usr/lib/init.d/00_drivers"
data = """
pcid /etc/pcid.d/
"""

[[files]]
path = "/usr/lib/init.d/20_orbital"
data = """
audiod
orbital orblogin launcher
"""
