# Default desktop configuration

include = ["../base.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 128
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
bootstrap = {}
coreutils = {}
drivers = {}
escalated = {}
extrautils = {}
initfs = {}
ion = {}
ipcd = {}
kernel = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils-background = {}
orbutils-launcher = {}
orbutils-orblogin = {}
ptyd = {}
smith = {}
userutils = {}
uutils = {}

# User settings
[users.root]
password = "password"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
pcid /etc/pcid.d/
escalated
"""

[[files]]
path = "/etc/init.d/20_orbital"
data = """
orbital orblogin launcher
"""

[[files]]
path = "/etc/init.d/30_console"
data = """
getty 2
getty debug: -J
"""

[[files]]
path = "/etc/redox-release"
data = "0.8.0"

[[files]]
path = "/etc/group"
data = """
root;0;root
user;1000;user
sudo;1;user
"""

[[files]]
path = "/etc/hostname"
data = """
redox
"""
