# Configuration for development, includes cargo and rustc

include = ["../net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 2048
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
audiod = {}
bash = {}
bootloader = {}
ca-certificates = {}
contain = {}
coreutils = {}
diffutils = {}
drivers = {}
extrautils = {}
findutils = {}
installer = {}
installer-gui = {}
ion = {}
netdb = {}
netsurf = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
pkgutils = {}
redoxfs = {}
relibc = {}
resist = {}
smith = {}
userutils = {}
uutils = {}

# CLI programs

curl = {}
git = {}
terminfo = {}
vim = {}


# Development tools
cargo = {}
crates-io-index = {}
gcc13 = {}
gnu-binutils = {}
gnu-make = {}
rust = {}

[[files]]
path = "/home/user/example.rs"
data = """
fn main() {
    println!("Hello, Redox!");
}
"""

[[files]]
path = "/etc/init.d/20_orbital"
data = """
audiod
orbital orblogin launcher
"""

[[files]]
path = "/etc/init.d/30_console"
data = """
getty 2
getty debug: -J
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"
