# Default desktop configuration

include = ["../net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
audiod = {}
bash = {}
bootloader = {}
ca-certificates = {}
contain = {}
coreutils = {}
diffutils = {}
extrautils = {}
findutils = {}
#installer = {} # failure to build ring
ion = {}
netdb = {}
#netsurf = {} # lots of porting issues
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
#pkgutils = {} # failure to build ring
redoxfs = {}
relibc = {}
resist = {}
smith = {}
userutils = {}
uutils = {}

[[files]]
path = "/etc/init.d/20_orbital"
data = """
audiod
orbital display:3/activate launcher
"""

[[files]]
path = "/etc/init.d/30_console"
data = """
getty display:2
getty debug: -J
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"
