# Default desktop configuration

include = ["../net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
audiod = {}
bash = {}
bootloader = {}
ca-certificates = {}
contain = {}
coreutils = {}
diffutils = {}
#drivers = {} # more porting work
#escalated = {} # porting
extrautils = {}
findutils = {}
#installer = {} # failure to build ring
ion = {}
ipcd = {}
netdb = {}
#netsurf = {} # lots of porting issues
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
#pkgutils = {} # failure to build ring
ptyd = {}
redoxfs = {}
relibc = {}
resist = {}
smith = {}
userutils = {}
uutils = {}

# User settings
[users.root]
password = "password"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
pcid /etc/pcid.d/
escalated
"""

[[files]]
path = "/etc/init.d/20_orbital"
data = """
audiod
orbital display:3/activate launcher
"""

[[files]]
path = "/etc/init.d/30_console"
data = """
getty display:2
getty debug: -J
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"

[[files]]
path = "/etc/group"
data = """
root;0;root
user;1000;user
sudo;1;user
"""
