# Default server configuration

include = ["../net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 512
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
bash = {}
bootloader = {}
ca-certificates = {}
contain = {}
coreutils = {}
diffutils = {}
extrautils = {}
findutils = {}
# FIXME: failed to build
# installer = {}
ion = {}
netdb = {}
# FIXME: failed to build
# pkgutils = {}
redoxfs = {}
resist = {}
smith = {}
userutils = {}
uutils = {}

git = {}
curl = {}
vim = {}

[[files]]
path = "/etc/init.d/30_console"
data = """
inputd -A 2
getty 2
getty debug: -J
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"
