# Minimal configuration

include = ["../../server-minimal.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256
# Do not prompt if settings are not defined
prompt = false
efi_partition_size = 128
