# Base configuration: This configuration is meant to be included by
# other configurations rather than use directly. It is the greatest
# common divisor of all other configurations and misses several
# parts necessary to create a bootable system.

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

[packages]
bootstrap = {}
escalated = {}
initfs = {}
ipcd = {}
kernel = {}
ptyd = {}

## Configuration files
[[files]]
path = "/usr/lib/init.d/00_base"
data = """
ipcd
ptyd
escalated
"""

[[files]]
path = "/etc/hostname"
data = """
redox
"""

[[files]]
path = "/etc/redox-release"
data = "0.8.0"

## Symlinks for usrmerge
[[files]]
path = "/usr"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/usr/bin"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/bin"
data = "usr/bin"
symlink = true

[[files]]
path = "/usr/include"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/include"
data = "usr/include"
symlink = true

[[files]]
path = "/usr/lib"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/lib"
data = "usr/lib"
symlink = true

[[files]]
path = "/usr/share"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/share"
data = "usr/share"
symlink = true

## /tmp directory with special mode
[[files]]
path = "/tmp"
data = ""
directory = true
mode = 0o1777

## Device file symlinks
[[files]]
path = "/dev/null"
data = "null:"
symlink = true

[[files]]
path = "/dev/random"
data = "rand:"
symlink = true

[[files]]
path = "/dev/urandom"
data = "rand:"
symlink = true

[[files]]
path = "/dev/zero"
data = "zero:"
symlink = true

[[files]]
path = "/dev/tty"
data = "libc:tty"
symlink = true

[[files]]
path = "/dev/stdin"
data = "libc:stdin"
symlink = true

[[files]]
path = "/dev/stdout"
data = "libc:stdout"
symlink = true

[[files]]
path = "/dev/stderr"
data = "libc:stderr"
symlink = true

# User settings
[users.root]
password = "password"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""

# Group settings
[groups.sudo]
gid = 1
members = ["user"]
