# Default desktop configuration

include = ["minimal-net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 128

# Package settings
[packages]
orbdata = {}
orbital = {}
orbterm = {}
orbutils-background = {}
orbutils-launcher = {}
orbutils-orblogin = {}

[[files]]
path = "/usr/lib/init.d/20_orbital"
data = """
orbital orblogin launcher
"""
