# Default desktop configuration

include = ["server-minimal.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 128

# Package settings
[packages]
drivers = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils-background = {}
orbutils-launcher = {}
orbutils-orblogin = {}

[[files]]
path = "/etc/init.d/00_drivers"
data = """
pcid /etc/pcid.d/
"""

[[files]]
path = "/etc/init.d/20_orbital"
data = """
orbital orblogin launcher
"""
