# Minimal configuration

include = ["base.toml"]

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
bootloader = {}
coreutils = {}
escalated = {}
extrautils = {}
ion = {}
ipcd = {}
ptyd = {}
smith = {}
userutils = {}
uutils = {}

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
escalated
"""

[[files]]
path = "/etc/init.d/30_console"
data = """
getty 2
getty debug: -J
"""
