# Default desktop configuration

include = ["../net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 512
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
audiod = {}
bash = {}
bootloader = {}
ca-certificates = {}
contain = {}
coreutils = {}
diffutils = {}
extrautils = {}
findutils = {}
installer = {}
installer-gui = {}
ion = {}
netdb = {}
netsurf = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
pkgutils = {}
redoxfs = {}
relibc = {}
resist = {}
smith = {}
userutils = {}
uutils = {}

git = {}
curl = {}
vim = {}

[[files]]
path = "/etc/init.d/20_orbital"
data = """
audiod
orbital contain_orblogin launcher
"""

[[files]]
path = "/etc/init.d/30_console"
data = """
getty 2
getty --contain debug: -J
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"

[[files]]
path = "/etc/contain.toml"
data = """
pass_schemes = ["rand", "null", "tcp", "udp", "thisproc", "pty", "orbital", "display.vesa"]
sandbox_schemes = ["file"]
files = ["file:/dev/null"]
rofiles = ["file:/etc/passwd", "file:/etc/hostname", "file:/etc/localtime"]
dirs = ["file:/tmp"]
rodirs = ["file:/bin", "file:/ui"]
"""
