# Jeremy's configuration

include = ["../net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 8192
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
audiod = {}
bash = {}
bootloader = {}
ca-certificates = {}
contain = {}
coreutils = {}
diffutils = {}
drivers = {}
escalated = {}
extrautils = {}
findutils = {}
installer = {}
installer-gui = {}
ion = {}
ipcd = {}
netdb = {}
netsurf = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
pkgutils = {}
ptyd = {}
redoxfs = {}
relibc = {}
relibc-tests = {}
resist = {}
smith = {}
userutils = {}
uutils = {}

# apps
cosmic-edit = {}
cosmic-files = {}
cosmic-term = {}
cosmic-text = {}
periodictable = {}
pixelcannon = {}
schismtracker = {}
sodium = {}

# cli
acid = {}
cleye = {}
curl = {}
ffmpeg6 = {}
git = {}
gnu-grep = {}
lua54 = {}
nano = {}
perg = {}
ripgrep = {}
rustpython = {}
sed = {}
shellharden = {}
vim = {}
xz = {}

# demos
cairodemo = {}
#cmatrix = {} # addwstr
cpal = {}
gears = {}
glium = {} # does not show anything
glutin = {}
hematite = {}
iced = {}
libcosmic = {}
orbclient = {}
osdemo = {} # does not show anything
pathfinder = {}
procedural-wallpapers-rs = {}
rodioplay = {}
rust-cairo = {}
rust-cairo-demo = {}
sdl2-gears = {}
vttest = {}
webrender = {}
winit = {}

# dev
autoconf = {}
automake = {}
#cargo = {} # openssl issues
#gcc13 = {} # libiberty errors
gnu-binutils = {}
gnu-make = {}
nasm = {}
patch = {}
pkg-config = {}
#rust = {} # takes too long to compile
rustpython = {}

# games
devilutionx = {}
dosbox = {}
eduke32 = {}
flycast = {}
freedoom = {}
gigalomania = {}
mednafen = {}
mgba = {}
neverball = {}
openjazz = {}
openjk = {}
openttd = {}
openttd-opengfx = {}
openttd-openmsx = {}
openttd-opensfx = {}
prboom = {}
redox-games = {}
#retroarch = {} # need to package cores
rs-nes = {} # need game for testing
rust64 = {} # need roms
rustual-boy = {} # need game for testing
scummvm = {} # need game for testing
sm64ex = {}
sopwith = {}
spacecadetpinball = {}
syobonaction = {}
#vice = {} # broken on new toolchain
vvvvvv = {}

# stuff
cosmic-icons = {}
freepats = {}
generaluser-gs = {}
intel-one-mono = {}
jeremy = {}
keyboard-sfx = {}
libc-bench = {}
noto-color-emoji = {}
pop-icon-theme = {}
terminfo = {}
timidity = {}
ttf-hack = {}

# User settings
[users.root]
password = "password"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""

[[files]]
path = "/etc/init.d/00_base"
data = """
ipcd
ptyd
pcid /etc/pcid.d/
escalated
"""

[[files]]
path = "/etc/init.d/20_orbital"
data = """
audiod
orbital orblogin launcher
"""

[[files]]
path = "/etc/init.d/30_console"
data = """
getty 2
getty debug: -J
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"

[[files]]
path = "/etc/group"
data = """
root;0;root
user;1000;user
sudo;1;user
"""
